from enum import Enum

class ErrorCode(str, Enum):
    PROJECT_SCOPE_UNSUPPORTED = "PROJECT_SCOPE_UNSUPPORTED"
    TOOL_NOT_INSTALLED = "TOOL_NOT_INSTALLED"
    TOOL_NOT_WRITABLE = "TOOL_NOT_WRITABLE"
    TARGET_EXISTS = "TARGET_EXISTS"
    SKILL_INVALID = "SKILL_INVALID"

    # 通用错误码
    INTERNAL_ERROR = "INTERNAL_ERROR"
